#!/bin/bash

cd ${0%/*}
cd ..

CARDANO_HW_CLI_PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')

# Remove old build
rm -R ./build/linux/archive-arm64 2> /dev/null

# Prepare directories
mkdir ./build/linux 2> /dev/null
mkdir ./build/linux/archive-arm64
mkdir ./build/linux/archive-arm64/cardano-hw-cli

# Build executable
#
# V8 bytecode can only be generated by executing a node binary of the target
# architecture. linux-arm64 bytecode cannot be produced on an x64 host, or on
# macOS, including Apple Silicon, where uname -m is arm64 but the linux-arm64
# node binary is not executable. pkg
# then emits an incomplete snapshot that crashes on startup (see issue #194).
# Fall back to --no-bytecode in those cases; native Linux arm64 builds keep
# bytecode packaging.
./scripts/prepare-pkg-native-deps.sh
HOST_OS="$(uname -s)"
HOST_ARCH="$(uname -m)"
PKG_EXTRA_OPTS=()
if [ "${HOST_OS}" != "Linux" ] || { [ "${HOST_ARCH}" != "aarch64" ] && [ "${HOST_ARCH}" != "arm64" ]; }; then
  echo "Cross-building linux-arm64 on ${HOST_OS}/${HOST_ARCH}: disabling bytecode to keep the snapshot intact (see issue #194)"
  PKG_EXTRA_OPTS=(--no-bytecode --public-packages '*' --public)
fi
yarn pkg ./dist/index.js -o ./build/linux/archive-arm64/cardano-hw-cli/cardano-hw-cli -c package.json -t node22-linux-arm64 --options "no-warnings=ExperimentalWarning" "${PKG_EXTRA_OPTS[@]}"

# Copy dependencies
cp -R ./build/dependencies/linux/* ./build/linux/archive-arm64/cardano-hw-cli/

# Archive
cd ./build/linux/archive-arm64
tar -czvf ./cardano-hw-cli-${CARDANO_HW_CLI_PACKAGE_VERSION}_linux-arm64.tar.gz ./cardano-hw-cli
cd ../../..
