#!/bin/bash

cd ${0%/*}
cd ..

CARDANO_HW_CLI_PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')

# Remove old build
rm -R ./build/linux/archive-arm64 2> /dev/null

# Prepare directories
mkdir ./build/linux 2> /dev/null
mkdir ./build/linux/archive-arm64
mkdir ./build/linux/archive-arm64/cardano-hw-cli

# Build executable
#
# V8 bytecode can only be generated by a binary of the target architecture.
# When cross-building (e.g. packaging linux-arm64 on an x64 machine) pkg
# silently produces an incomplete snapshot and the resulting executable
# crashes on startup with MODULE_NOT_FOUND (see issue #194). Fall back to
# --no-bytecode in that case; native arm64 builds keep bytecode packaging.
PKG_EXTRA_OPTS=()
if [ "$(uname -m)" != "aarch64" ] && [ "$(uname -m)" != "arm64" ]; then
  echo "Cross-building linux-arm64 on $(uname -m): disabling bytecode to keep the snapshot intact (see issue #194)"
  PKG_EXTRA_OPTS=(--no-bytecode --public-packages '*' --public)
fi
yarn pkg ./dist/index.js -o ./build/linux/archive-arm64/cardano-hw-cli/cardano-hw-cli -c package.json -t node22-linux-arm64 --options "no-warnings=ExperimentalWarning" "${PKG_EXTRA_OPTS[@]}"

# Copy dependencies
cp -R ./build/dependencies/linux/* ./build/linux/archive-arm64/cardano-hw-cli/

# Archive
cd ./build/linux/archive-arm64
tar -czvf ./cardano-hw-cli-${CARDANO_HW_CLI_PACKAGE_VERSION}_linux-arm64.tar.gz ./cardano-hw-cli
cd ../../..
